name: Build Serd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.10

      - name: Install BinaryBuilder
        run: |
          julia -e '
            import Pkg;
            Pkg.add("BinaryBuilder");
          '

      - name: Run build_tarballs.jl
        run: julia build_tarballs.jl

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: serd-binaries
          path: products
